### ISSUE TITLE
as missiles on servers

### ISSUE THREAD

**Issue by RagexPrince683** [RagexPrince683/MCH-mocmaster#3]
[18:45:27] [Server thread/ERROR] [FML]: There was a critical exception handling a packet on channel MCHeli_CH
java.lang.NoClassDefFoundError: net/minecraft/client/particle/EntityFX
        at mcheli.weapon.MCH_WeaponASMissile.shot(MCH_WeaponASMissile.java:73) ~[MCH_WeaponASMissile.class:?]
        at mcheli.weapon.MCH_WeaponBase.use(MCH_WeaponBase.java:171) ~[MCH_WeaponBase.class:?]
        at mcheli.weapon.MCH_WeaponSet.use(MCH_WeaponSet.java:370) ~[MCH_WeaponSet.class:?]
        at mcheli.aircraft.MCH_EntityAircraft.useCurrentWeapon(MCH_EntityAircraft.java:4840) ~[MCH_EntityAircraft.class:?]
        at mcheli.tank.MCH_TankPacketHandler.onPacket_PlayerControl(MCH_TankPacketHandler.java:75) ~[MCH_TankPacketHandler.class:?]
        at mcheli.MCH_PacketHandler.onPacket(MCH_PacketHandler.java:136) ~[MCH_PacketHandler.class:?]
        at mcheli.wrapper.W_PacketHandler.onMessage(W_PacketHandler.java:44) ~[W_PacketHandler.class:?]
        at mcheli.wrapper.W_PacketHandler.onMessage(W_PacketHandler.java:30) ~[W_PacketHandler.class:?]
        at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
        at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
        at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
        at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.particle.EntityFX
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_381]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_381]
        ... 27 more
Caused by: java.lang.NullPointerException
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_381]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_381]
        ... 27 more
[18:45:27] [Server thread/INFO]: RagexPrince683 lost connection: TextComponent{text='A fatal error has occured, this connection is terminated', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[18:45:27] [Server thread/INFO]: RagexPrince683 left the game

**Comment by RagexPrince683** [comment]
why

**Comment by RagexPrince683** [comment]
FUC

**Comment by RagexPrince683** [comment]
the problem was the deprecated method, just using the old default one for now.

**Comment by RagexPrince683** [comment]
Yeah I never got this working on multiplayer so it never worked. Probably was something to do with marking targets being a client side render although that makes zero sense. I still have no idea what caused this to error on multiplayer.

**Comment by RagexPrince683** [comment]
pain.
